### House Prices Prediction

In this exercise you'll try to build a neural network that predicts the price of a house according to a simple formula.

So, imagine if house pricing was as easy as a house costs 50k + 50k per bedroom, so that a 1 bedroom house costs 100k, a 2 bedroom house costs 150k etc.

How would you create a neural network that learns this relationship so that it would predict a 7 bedroom house as costing close to 400k etc.

Hint: Your network might work better if you scale the house price down.
You don't have to give the answer 400...it might be better to create something that predicts the number 4, and then your answer is in the 'hundreds of thousands' etc.

In [1]:
hc = 50000
pbr = 50000
def get_house_price(no_of_bedrooms):
    return hc+pbr*no_of_bedrooms

In [35]:
get_house_price(4)

250000

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [13]:
import random

In [25]:
xs = [random.randrange(1,10) for i in range(100)]
ys = [get_house_price(x) for x in xs]
xs = np.array(xs)
ys=np.array(ys)
# scaling ys
ys = ys/100000

In [28]:
xs[:10]

array([3, 8, 6, 4, 4, 9, 8, 3, 7, 1])

In [29]:
ys[:10]

array([2. , 4.5, 3.5, 2.5, 2.5, 5. , 4.5, 2. , 4. , 1. ])

In [31]:
model = keras.models.Sequential([keras.layers.Dense(units=1,input_shape = [1])])

In [32]:
model.compile(optimizer='sgd',loss='mean_squared_error')

In [33]:
model.fit(xs,ys,epochs=500)

Train on 100 samples
Epoch 1/500
100/100 [==============================] - 0s 2ms/sample - loss: 0.3784
Epoch 2/500
100/100 [==============================] - 0s 61us/sample - loss: 0.0718
Epoch 3/500
100/100 [==============================] - 0s 57us/sample - loss: 0.0673
Epoch 4/500
100/100 [==============================] - 0s 62us/sample - loss: 0.0658
Epoch 5/500
100/100 [==============================] - 0s 61us/sample - loss: 0.0632
Epoch 6/500
100/100 [==============================] - 0s 52us/sample - loss: 0.0589
Epoch 7/500
100/100 [==============================] - 0s 53us/sample - loss: 0.0582
Epoch 8/500
100/100 [==============================] - 0s 62us/sample - loss: 0.0560
Epoch 9/500
100/100 [==============================] - 0s 54us/sample - loss: 0.0545
Epoch 10/500
100/100 [==============================] - 0s 62us/sample - loss: 0.0511
Epoch 11/500
100/100 [==============================] - 0s 53us/sample - loss: 0.0506
Epoch 12/500
100/100 [=====================

In [34]:
model.predict([4])

array([[2.4999948]], dtype=float32)